spring:
  daasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: D0best42o
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

